metric: COCO
num_classes: 6

TrainDataset:
  !COCODataSet
    image_dir: images
    anno_path: /home/yaozhuohan/bxy/PaddleDetection/dataset/coco/annotations/voc_train.json
    dataset_dir: /home/yaozhuohan/bxy/PaddleDetection/dataset/coco
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: images
    anno_path: /home/yaozhuohan/bxy/PaddleDetection/dataset/coco/annotations/voc_valid.json
    dataset_dir: /home/yaozhuohan/bxy/PaddleDetection/dataset/coco

TestDataset:
  !ImageFolder
    anno_path: /home/yaozhuohan/bxy/PaddleDetection/dataset/coco/label_list.txt # also support txt (like VOC's label_list.txt)
    dataset_dir: /home/yaozhuohan/bxy/PaddleDetection/dataset/coco # if set, anno_path will be 'dataset_dir/anno_path'
